export const HACKER_NEWS_FETCH_REQUEST = 'HACKER_NEWS_FETCH_REQUEST';
export const HACKER_NEWS_FETCH_SUCCESS = 'HACKER_NEWS_FETCH_SUCCESS';
export const HACKER_NEWS_FETCH_FAILURE = 'HACKER_NEWS_FETCH_FAILURE';
